### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by salsilago** [florian-mollin/yapi#2]
I've imported the jar. As soon as I write the constructor (as stated in the instructions), I get the error message "Unhandled exception: com.mollin.yapi.exception.YeelightSocketException". What am I doing wrong?

**Comment by florian-mollin** [comment]
Hello,

Thank you for using Yapi.
As you can see, the project is unfortunately no longer really maintained (but PR are welcomed).
Your error, can come from different sources. The API is tested with the Yeelight bulb V1, I don't know if it still works with the V2.

A few things to help you:
- Check the version of your bulb
- Check that your bulb and your program are on the same network (and IP address of the bulb is the right one)
- Make sure your bulb is in "development" mode
